### ISSUE TITLE
Issue starting plex media server on Odroid XU4 

### ISSUE THREAD

**Issue by CatalinMustata** [tproenca/pmsarm7#4]
I've installed it using the supplied instructions on an Odroid XU4 running Ubuntu 16.04. Installation seemed to be successful but trying to start the server failed without any error.

Is there any place I should look for signs of failure? I can't figure out what's wrong with it.

**Comment by tproenca** [comment]
Actually I don't... I'm actually using the previous version of Ubuntu. I'm gonna upgrade this week and let you know my findings...

**Comment by Jorricks** [comment]
So what I found out is that the original service links to /usr/sbin/start_pms.
By launching ./start_pms it gives you the error that you should provide a serverUuid.
So I launched ./start_pms --serviceUuid='jorricks' and launching it from there worked.

Update:
I found out that since I defined a serviceUuid I can just use ./start_pms to run the program. Still figuring out where it goes wrong.

Update #2:
Fixed the script.
I found some very weird line in the service script.
In /etc/init.d/plexmediaserver there is the following line
`test -f "/usr/lib/plexmediaserver/start.sh" || exit 0`
What this code does is that it checks if it can find the file, if this returns true, it stops, if it returns false it exits 0. This means that as the file does not exists anymore in the latest version(weird..), it exits.
Therefore by commenting this line out your server will start :)!
Note that if you launch `service plexmediaserver start` it will give you the error that you should run 'systemctl daemon-reload'. Simply execute this command and your done.


Note:
Btw to @tproenca you should really mention how to change the config... 
Please add at least a note of the file in /etc/default/plexmediaserver (which is the config used).
I created a pull request with both the update I found and the settings option.

**Comment by CatalinMustata** [comment]
That sounds very encouraging. I'll give it a try in the following days and report back if it works for me.

**Comment by Jorricks** [comment]
@CatalinMustata Did it solve it for you :)?

**Comment by CatalinMustata** [comment]
Still doesn't work for me, but I've noticed there's no `/usr/bin/start_pms` on my system. I will try a reinstall.

Update: reinstalled and I have version `1.8.1.4139` now, but still no joy. There is no `/usr/bin/start_pms` 

Update 2: Wow, I'm really tired... only now did I notice I needed to look in `sbin` and not `bin`. Works fine now.

**Comment by Jorricks** [comment]
Awesome! Happy I could help!

**Comment by cybercussion** [comment]
Thanks /usr/sbin/start_pms helped .. am I supposed to pass a --serverUuid ?
